from fastapi import FastAPI, Body
from fastapi.middleware.cors import CORSMiddleware
from config import gemini_client, chats_collection, support_tickets
import uuid
from google.genai import types
from pydantic import BaseModel

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=['http://127.0.0.1:5173'],
    allow_methods=["*"],
    allow_headers=["*"],
    allow_credentials=True
)

@app.get("/")
async def read_root():
    return {"message": "Hello! This is a FastAPI server for an E-commerce live chat customer support agent that uses Google Gemini."}

async def create_support_ticket(session_id: str, ticket_issue: str):
    ticket_number = uuid.uuid4()
    await support_tickets.insert_one({
        "session_id": session_id,
        "ticket_issue": ticket_issue
    })
    return f"Your ticket has been created with ticket number {ticket_number}. We will get back to you as soon as we can."

class ChatModel(BaseModel):
    session_id: str
    message: str

create_support_ticket_function = {
    "name": "create_support_ticket",
    "description": "Creates a support ticket once the user needs escalation of the problem.",
    "parameters": {
        "type": "object",
        "properties": {
            "session_id": {
                "type": "string",
                "description": "The session_id of the chat."
            },
            "ticket_issue": {
                    "type": "string",
                    "description": "Description generated by bot."
                }
            },
        "required": ["session_id", "ticket_issue"]
    }
}

@app.post("/chat")
async def chat_with_bot(chat_body: ChatModel):
    session_id = chat_body.session_id
    message = chat_body.message

    chat_history = await chats_collection.find_one({"_id": session_id})

    if not chat_history:
        base_chat = [
            f"This chat's session_id: {session_id}",
            "You are an E-commerce customer support agent named Eric and you are assigned to inquiries related to Orders.",
            "To be an effective customer support, do not repeat previous contexts like your name.",
            "Start the conversation by asking the customer's name, and what Order is he/she having troubles with.",
            """The user only has three orders: [
                {id: "001", item: "MacBook", status: "Shipped"},
                {id: "002", item: "Samsung Galaxy Z Flip 6", status: "Processing"},
                {id: "003", item: "Keychron K6", status: "Delivered"}
            ]""",
            "Converse with the user with courtesy and patience. If the issue needs escalation, ask the user if it's fine to escalate and generate a ticket."
        ]
        new_chats = []
        for i in base_chat:
            new_chats.append({"role": "system", "message": i})
        new_chats.append({"role": "user", "message": message})

        print("now inserting to mongodb")
        base_chat_model = {
            "_id": session_id,
            "chats": new_chats
        }
        await chats_collection.insert_one(base_chat_model)
        chat_history = await chats_collection.find_one({"_id": session_id})
    else:
        print("found existing conversation")
        chat_history_list = chat_history.get("chats")
        chat_history_list.append({"role": "user", "message": message})

    chat_history_list = chat_history.get("chats")
    chat_contents = str(chat_history_list) 

    tools = types.Tool(function_declarations=[create_support_ticket_function])
    config = types.GenerateContentConfig(tools=[tools])

    response = gemini_client.models.generate_content(
        model="gemini-2.0-flash",
        contents=chat_contents,
        config=config
    )

    if response.candidates[0].content.parts[0].function_call:
        function_call = response.candidates[0].content.parts[0].function_call
        print(f"Function to call: {function_call.name}")
        print(f"Arguments: {function_call.args}")
        reply = await create_support_ticket(**function_call.args)
    else:
        reply = response.text
    print("now appending reply to the chats history")
    await chats_collection.update_one(
        {"_id": session_id}, 
        {"$addToSet": {"chats": {"role": "model", "message": reply}}}
        )

    return {"reply": reply}

