from fastapi import FastAPI, Body
from fastapi.middleware.cors import CORSMiddleware
from config import gemini_client, orders_collection, chats_collection, support_tickets_collection
import uuid
from google.genai import types
from pydantic import BaseModel
import json

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=['http://127.0.0.1:5173'],
    allow_methods=["*"],
    allow_headers=["*"],
    allow_credentials=True
)

@app.get("/")
async def read_root():
    return {"message": "Hello! This is a FastAPI server for an E-commerce live chat customer support agent that uses Google Gemini."}

@app.get("/orders")
async def get_orders():
    orders = await orders_collection.find({}, {"_id": 0}).to_list(None)
    if orders:
        new_orders = []
        for i in orders:
            i['related_tickets'] = await support_tickets_collection.count_documents({"order_id": i['order_id']})
            new_orders.append(i)
        return {
            "orders": new_orders
        }
    else:
        with open('orders.json', 'r') as file:
            orders = json.load(file)
        new_orders = []
        await orders_collection.insert_many(orders)
        return {
            "orders": orders
        }

async def create_support_ticket(session_id: str, order_id: int, ticket_issue: str):
    ticket_number = uuid.uuid4()
    await support_tickets_collection.insert_one({
        "session_id": session_id,
        "order_id": order_id,
        "ticket_issue": ticket_issue
    })
    return f"""Your escalation ticket has been created with ticket number {ticket_number}. We will get back to you as soon as we can.
    Do you have anything else that you need assistance with?"""

class ChatModel(BaseModel):
    session_id: str
    message: str

create_support_ticket_function = {
    "name": "create_support_ticket",
    "description": "Creates a support ticket once the user needs escalation of the problem.",
    "parameters": {
        "type": "object",
        "properties": {
            "session_id": {
                "type": "string",
                "description": "The session_id of the chat."
            },
            "order_id": {
                    "type": "integer",
                    "description": "The order_id based on the conversation."
            },
            "ticket_issue": {
                    "type": "string",
                    "description": "Description generated by bot."
                }
        },
        "required": ["session_id", "order_id", "ticket_issue"]
    }
}

async def verify_order_details(order_id: str):
    order_details = await orders_collection.find_one({"order_id": order_id}, {"_id": 0})    
    return order_details

verify_order_details_function = {
    "name": "verify_order_details",
    "description": "Pulls the order details from the Mongodb database.",
    "parameters": {
        "type": "object",
        "properties": {
            "order_id": {
                    "type": "integer",
                    "description": "The order_id based on the conversation."
            }
        },
        "required": ["order_id"]
    }    
}

async def verify_all_order_details():
    order_details = await orders_collection.find({}, {"_id": 0}).to_list(None)
    return order_details

verify_all_order_details_function = {
    "name": "verify_all_order_details",
    "description": "Pulls all of the order details from the Mongodb database."
}

@app.post("/chat")
async def chat_with_bot(chat_body: ChatModel):
    session_id = chat_body.session_id
    message = chat_body.message

    chat_proceed = False
    while chat_proceed == False:
        chat_history = await chats_collection.find_one({"_id": session_id})

        if not chat_history:
            base_chat = [
                f"This chat's session_id: {session_id}",
                "You are an E-commerce customer support agent named Eric and you are assigned to inquiries related to Orders.",
                "Start the conversation by asking the customer's name, and what Order is he/she having troubles with.",
                "If you can't understand the user's inquiry due to lack of details about the order, you can capture details using verify_order_details function.",
                "User might not be able to send the order_id for the verify_order_details, do not force the user, instead you can retrieve all of the order details using verify_all_order_details function."
                "Converse with the user with courtesy and patience. If the issue needs escalation, ask the user if it's fine to escalate and generate a ticket."
            ]
            new_chats = []
            for i in base_chat:
                new_chats.append({"role": "system", "message": i})
            new_chats.append({"role": "user", "message": message})

            print("now inserting to mongodb")
            base_chat_model = {
                "_id": session_id,
                "chats": new_chats
            }
            await chats_collection.insert_one(base_chat_model)
            chat_history = await chats_collection.find_one({"_id": session_id})
        else:
            print("found existing conversation")
            chat_history_list = chat_history.get("chats")
            chat_history_list.append({"role": "user", "message": message})

        chat_history_list = chat_history.get("chats")
        chat_contents = str(chat_history_list) 

        tools = types.Tool(function_declarations=[create_support_ticket_function, verify_order_details_function, verify_all_order_details_function])
        config = types.GenerateContentConfig(tools=[tools])

        print("now prompting to gemini")
        response = gemini_client.models.generate_content(
            model="gemini-2.0-flash",
            contents=chat_contents,
            config=config
        )
        if response.candidates[0].content.parts[0].function_call:
            function_call = response.candidates[0].content.parts[0].function_call
            print(f"Function to call: {function_call.name}")
            print(f"Arguments: {function_call.args}")
            if function_call.name == "verify_order_details":
                order_details = await verify_order_details(**function_call.args)
                await chats_collection.update_one(
                    {"_id": session_id}, 
                    {"$addToSet": {"chats": {"role": "system", "message": order_details}}}
                )
            elif function_call.name == "verify_all_order_details":
                all_order_details = await verify_all_order_details()
                await chats_collection.update_one(
                    {"_id": session_id}, 
                    {"$addToSet": {"chats": {"role": "system", "message": all_order_details}}}
                )
            else:
                reply = await create_support_ticket(**function_call.args)
                print("now appending reply of the support ticket to the chats history")
                await chats_collection.update_one(
                    {"_id": session_id}, 
                    {"$addToSet": {"chats": {"role": "model", "message": reply}}}
                    )
                chat_proceed = True
        else:
            reply = response.text
            print("now appending reply to the chats history")
            await chats_collection.update_one(
                {"_id": session_id}, 
                {"$addToSet": {"chats": {"role": "model", "message": reply}}}
                )
            chat_proceed = True

        return {"reply": reply}

